### ISSUE TITLE
"Animate transition" option does not work as expected

### ISSUE THREAD

**Issue by tdobes** [briangann/grafana-gauge-panel#14]
Tested using Firefox 51.0.1:

When the "animate transition" property is enabled, the needle moves quickly (with an animation) from value to value.

When the "animate transition" property is disabled, the needle is still animated, but moves much more slowly from value to value.

It appears that the needle motion is animated regardless of the setting of this option.  (There is no way to disable the needle animation and cause it to "click" between values instantly.)  Perhaps this should be a numeric option instead of a boolean, specifying the needle transition time in milliseconds or seconds.  (Disabling the animation entirely could be represented by a value of zero.)

**Comment by briangann** [comment]
It looks like it is actually inverted - the animate option when "checked" is supposed to move slowly from value to value, and when unchecked it is supposed to "snap" to the new value.  There's a bounce option also that's disabled by default.

A configurable transition time is a great idea, making it much more flexible.

**Comment by briangann** [comment]
The fix for this has been pushed, there's a new option to set the speed of animation. Unchecking the animate box will now "snap" to the new location too.

I also changed the transition from "elastic" to "quadin" to remove the "bounce."

I can add in a selector for transition types if that is desired, there's at least 15 different types.

**Comment by briangann** [comment]
v0.0.3 fixes these issues, thanks!
